#!/bin/bash

##/media/bruno/T7/devkit-1.1-FC/LINUX/android/vendor

SOURCE_FILES=""
SOURCE_FILES+=" qcom/proprietary/chi-cdk/tools/buildbins/buildbins_kona.yaml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/Android.mk"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/s5kgw1_cphy/build/linuxembedded/CMakeLists.txt"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/core/build/linuxembedded/CMakeLists.txt"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/configs/product.mk"
SOURCE_FILES+=" qcom/proprietary/common/config/device-vendor.mk"
SOURCE_FILES+=" qcom/proprietary/common/config/device-vendor-qssi.mk"
SOURCE_FILES+=" qcom/proprietary/common/config/device-vendor-SDM845-pureAOSP.mk"
SOURCE_FILES+=" qcom/proprietary/display-devicetree/display/dsi-panel-vq910-dualmipi-video-id1.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-qupv3.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-pinctrl.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-mtp.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-xr.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-mtp.dtsi.skyworth"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-mtp.dtsi.QUP8"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-sde-display.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-mtp.dtsi.back"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-rb5.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-v2.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona-hdk.dtsi"
SOURCE_FILES+=" qcom/proprietary/devicetree-4.19/qcom/kona.dtsi.back"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/build/android"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/build/android/Android.mk"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/imx471_sensor.cpp"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/imx471_sensor.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/module/sunny_imx471_module_1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/module/sunny_imx471_module_3.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/module/sunny_imx471_module_0.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/module/sunny_imx471_module_2.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/imx471_sensor.cpp"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/sensor/imx471/imx471_sensor.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/ImagePool.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/XSD.cxl"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/project.txt"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/XML.cxl"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Presets.cxl"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/demosaic36_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/hdr30_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/gtm10_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/gamma16_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/lsc40_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/pdpc30_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/ds4to1v10_bps_full_dc4.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/pedestal13_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/linearization34_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/ds4to1v10_bps_dc4_dc16.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/bls12_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/cst12_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/bincorr10_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/gic30_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/demux13_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/cc13_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/BPS/abf40_bps.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/asf30_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ds4to1v11_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/gamma15_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/upscale20_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cac23_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cc13_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cv12_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ltm14_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/tf20_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ica30_ipe_module2.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ica20_ipe_module2.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cst12_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/sce11_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cs20_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/hnr10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/lenr10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ds4to1v10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/cvp10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ica20_ipe_module1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/ica30_ipe_module1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/tdl10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/anr10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IPE/gra10_ipe.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/bls12_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/pedestal13_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/demux13_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/bincorr10_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/ds4to1v11_ife_disp_dc4_dc16.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/ds4to1v11_ife_video_dc4_dc16.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/cc13_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/hdr30_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/gamma16_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/dsx10_ife_video_full_dc4.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/ds4to1v11_ife_disp_full_dc4.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/demosaic36_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/cst12_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/pdpc30_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/linearization34_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/gtm10_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/abf40_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/IFE/lsc40_ife.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/bgStatsConfigV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFMLCZV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixAFMONITOR.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SensorHDRDefaultConfig.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFSpectralSensorAssistV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/sensorCalV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/ChromatixASDTuningData.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFMLCZV2.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Flash.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFSubSmpV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SAAGWV2.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixAFTuningSoftwareStatistics.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/ledTorchV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Touch.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SAAGWV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/aecDepth.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixContrastAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/StartUp.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/ChromatixAFDTuningData.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/initDataV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixHAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFGeneralWVV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixAFAlgoTuning.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/refPtV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/flashRefPtV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Face.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/faceROIProcessorV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/tmpConvV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/flashDecV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixTOF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFIlluWVV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/DSFV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/faceAssistV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/AECParamExtension.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixAFExtension.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/histCtrlV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Extension.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixDCIAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/StatsDefaultConfig.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixDepthAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Metering.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixPDAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/lcdFlashV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixPDLib.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/aecMultiCamSync.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SAGenV2DataArray.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/chromatixBAF.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/aecSkipCtrl.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFStatScrV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SASpatialGenV1DataArray.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/MWBGainV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Tracker.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Convergence.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/triglGAV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/ChromatixRERTuningData.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/Arbitration.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/flashWV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/aecGyro.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SnapshotControl.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/bestShotV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/AWBExtensionParam.xm"l
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/custRefPtV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/DAV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/awbSceneChangeConvergeV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SAGenV1DataArray.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/dualcamSyncV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFDistWVV1.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/STATS/SFMLCZV3.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/tintless20_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/mf11_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/tmc12_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/video10_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/hdrvideo10_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/shdr10_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/eis12_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/XML/SW_CONTROL/ldc10_sw.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/Scenario.Default/sensorData.xml"
SOURCE_FILES+=" qcom/proprietary/chi-cdk/oem/qcom/tuning/sm8250_sunny_imx471/settings.xml"

DEST_DIR="~/acheul/BSP/Acheul-SOM/DevKit-patch"

for current_file in ${SOURCE_FILES} ;
do
    file_path="$(echo ${current_file} | sed 's|\(.*\)\/.*|\1|g')"
    file_name="$(echo ${current_file} | sed 's|.*\/\(.*\)|\1|g')"
    dest_path="${DEST_DIR}/${file_path}"

    ##
    #echo "current file: ${current_file}"
    #echo "path        : ${file_path}"
    #echo "path        : ${file_name}"
    #echo "dest_path   : ${dest_path}"
    ##

    #echo "mkdir -v -p ${dest_path}"
    echo "cp -v ${current_file} ${dest_path}"
done

